### ISSUE TITLE
Change copy to "Shoot us a DM at @elfabetorg on twitter or instagram". also make our email a link

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#10]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/60150a92-6fc0-4119-b15b-470f1adc7056.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/4f92375a-d9ca-41eb-8a09-42e70ef813cd.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/contact](https://helpful-custard-03b644.netlify.app/contact)

**Device and browser info:**
Chrome 109.0.0.0 (1280x581) | Windows 10

**Date and time:**
February 5th 2023 | 5:39am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/42661bb1-2324-422b-abc5-fac7cab72c7e](https://jam.dev/c/42661bb1-2324-422b-abc5-fac7cab72c7e)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
Also added links to Twitter and Instagram because I'm awesome that way.

**Comment by honeybutterball** [comment]
It didnt update on my laptop though
[image: image.png]
