### ISSUE TITLE
is it allow or allows

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#16]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/57be2e44-beec-42fa-8353-3d7f10419232.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/4553c428-a179-4cef-91b6-12eb9879b95d.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/](https://helpful-custard-03b644.netlify.app/)

**Device and browser info:**
Chrome 109.0.0.0 (1280x581) | Windows 10

**Date and time:**
February 8th 2023 | 1:50am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/6354ec57-ba8d-4450-b201-a2466b9ddfcb](https://jam.dev/c/6354ec57-ba8d-4450-b201-a2466b9ddfcb)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
It's allow. Everyone is grammatically singular
