### ISSUE TITLE
i think maybe we bold 'without losing your sanity (& your life savings)'

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#17]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/4336f272-9704-46b7-932d-f4088607cfe4.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/4dac32f2-2ec6-4c39-957c-3eb5e8d576e6.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/](https://helpful-custard-03b644.netlify.app/)

**Device and browser info:**
Chrome 109.0.0.0 (1280x581) | Windows 10

**Date and time:**
February 8th 2023 | 2:17am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/cfd9866f-e6c3-45fd-9080-0363b5abdeaf](https://jam.dev/c/cfd9866f-e6c3-45fd-9080-0363b5abdeaf)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
I disagree
