### ISSUE TITLE
Swap placement of these two

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#25]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/3d8b7284-6ef1-49b5-a1d8-9897469e090e.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/40fe4161-62e0-4322-ac14-36a28a91ad46.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/about](https://helpful-custard-03b644.netlify.app/about)

**Device and browser info:**
Chrome 110.0.0.0 (1280x581) | Windows 10

**Date and time:**
February 23rd 2023 | 12:53am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/9f949625-b6cd-4e03-b692-8694a292c3ce](https://jam.dev/c/9f949625-b6cd-4e03-b692-8694a292c3ce)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
I agree with you but just for next time:
(1) I won't always fix stuff like this if I disagree with the design decision
(2) Put some kind of reasoning unless it's a bug fix or something is very obviously wrong with the page

**Comment by honeybutterball** [comment]
My reasoning isi that it will look better
