### ISSUE TITLE
Please please please more white space between these please

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#26]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/67261025-737c-4dd3-ac2c-e88063befcb8.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/bb473fba-bb8f-4c49-9e3a-d0d0b4a80ceb.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/](https://helpful-custard-03b644.netlify.app/)

**Device and browser info:**
Chrome 110.0.0.0 (1280x581) | Windows 10

**Date and time:**
February 23rd 2023 | 12:55am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/90247f5a-7683-40d6-9fad-046f8bbc0f68](https://jam.dev/c/90247f5a-7683-40d6-9fad-046f8bbc0f68)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
What?? Since when did this happen??? AGGGGHHHHHH it was literally normal yesterday

**Comment by arielCheng218** [comment]
Does this happen when the page first loads or does it always happen

**Comment by honeybutterball** [comment]
Always

**Comment by arielCheng218** [comment]
@honeybutterball How does it look now?

**Comment by arielCheng218** [comment]
@honeybutterball Can I see how it looks when you scroll up? Like is there just too little white space at the bottom or is the entire thing squashed?

**Comment by arielCheng218** [comment]
Should be fixed now
