### ISSUE TITLE
@honeybutterball 

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#27]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/ab78f707-223a-47f7-9f4f-be7f4fc57526.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/39cfcc0f-91ec-4b30-b2ee-12c80ad681a5.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/about](https://helpful-custard-03b644.netlify.app/about)

**Device and browser info:**
Chrome 110.0.0.0 (1280x581) | Windows 10

**Date and time:**
February 24th 2023 | 3:46am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/997ad44c-cc76-4d83-9e5d-01fd29733845](https://jam.dev/c/997ad44c-cc76-4d83-9e5d-01fd29733845)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
AHHHHHH Sorry but I thought you told me to change it to @Abigail but will fix >:(
