### ISSUE TITLE
Bug caught on helpful-custard-03b644.netlify.app

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#3]
WORKS

**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/924407be-4028-4ba2-ac65-e34e65cff4ae.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/f3babf03-c06c-450b-b31a-a4d0d484ea35.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/](https://helpful-custard-03b644.netlify.app/)

**Device and browser info:**
Chrome 109.0.0.0 (1280x517) | Windows 10

**Date and time:**
January 27th 2023 | 1:10pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/4d2b7e18-445f-45fb-abf0-b2d9ec1000ba](https://jam.dev/c/4d2b7e18-445f-45fb-abf0-b2d9ec1000ba)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
Nice!!
