### ISSUE TITLE
can you add 'even' before 'a laundry list'

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#32]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/c1aca9b5-cd30-46b8-b540-c1e08aa922af.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/a4a88cdc-b28f-4d8e-8a59-6ecddc989779.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/contact](https://helpful-custard-03b644.netlify.app/contact)

**Device and browser info:**
Chrome 110.0.0.0 (1280x581) | Windows 10

**Date and time:**
February 27th 2023 | 12:06pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/e421dbde-bcc4-48ae-ba98-4b26b718548e](https://jam.dev/c/e421dbde-bcc4-48ae-ba98-4b26b718548e)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
Done
