### ISSUE TITLE
Bug caught on helpful-custard-03b644.netlify.app

### ISSUE THREAD

**Issue by honeybutterball** [elfabetorg/elfabet#4]
**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/2291c0f3-deaf-4254-be28-d0f600678de6.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/765735e4-ac06-4d48-944a-4a05470257e9.png)

\-------------------------------------

**Website URL:**
[https://helpful-custard-03b644.netlify.app/](https://helpful-custard-03b644.netlify.app/)

**Device and browser info:**
Chrome 109.0.0.0 (1280x581) | Windows 10

**Date and time:**
February 1st 2023 | 12:56am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/cb943a6e-1f26-46ec-9f5c-ffabc6fe1ee0](https://jam.dev/c/cb943a6e-1f26-46ec-9f5c-ffabc6fe1ee0)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by arielCheng218** [comment]
@honeybutterball where's the file you sent? Put it on figma

**Comment by arielCheng218** [comment]
Fixed.
